Repository Teed-Corp/teedhouse, pull requests merged in 2024-04, with the labels that each got.

#30 FEAT: Add Navigation
  App.tsx
  app/screens/choose_family/ChooseFamilyPage.tsx
  app/screens/login/components/AuthCard.tsx
  package.json
  yarn.lock
Labels: enhancement

#32 Ajout du SafeAreaProvider
  App.tsx
  app/screens/login/LoginPage.tsx
  app/screens/login/components/AuthCard.tsx
Labels: enhancement

#33 FEAT: creation de la page pour choisir de rejoindre ou créer un groupe
  App.tsx
  app/screens/choose_family/ChooseFamilyPage.tsx
  app/screens/choose_family/components/GroupButton.tsx
Labels: enhancement

#34 5 feat create group page
  App.tsx
  app/components/Content/HeaderIcon.tsx
  app/components/Content/HeaderTitle.tsx
  app/components/Divider.tsx
  app/components/Inputs/AppButton.tsx
  app/components/Inputs/CustomDropdown.tsx
  app/components/Inputs/CustomTextField.tsx
  app/screens/chooseGroup/ChooseGroupPage.tsx
  app/screens/chooseGroup/components/GroupButton.tsx
  app/screens/group/CreateGroupPage.tsx
  app/screens/login/components/AuthCard.tsx
  package.json
  yarn.lock
Labels: enhancement

#40 FEAT: creation de la page rejoindre un groupe
  App.tsx
  app/screens/group/JoinGroupPage.tsx
Labels: enhancement

#41 GH:23 Créer les méthodes de gestions des familles
  app/hooks/Auth.ts
  app/hooks/Family.ts
  app/screens/login/LoginPage.tsx
  package.json
  prisma/migrations/20240326160724_/migration.sql
  prisma/migrations/20240408080450_/migration.sql
  prisma/schema.prisma
  yarn.lock
Labels: enhancement

#42 Feat (Create Group): Form dans Page Créer un groupe
  App.tsx
  app/components/Content/ErrorText.tsx
  app/components/Inputs/CustomDropdown.tsx
  app/screens/group/CreateGroupPage.tsx
  app/screens/login/components/AuthCard.tsx
  app/theme/theme.tsx
Labels: enhancement

#44 style: fix shadow sur Ios
  app/screens/chooseGroup/ChooseGroupPage.tsx
  app/screens/chooseGroup/components/GroupButton.tsx
Labels: bug, enhancement

#45 Refacto: Changer "Group" en "Famille"
  App.tsx
  app/components/Content/ErrorText.tsx
  app/navigation/routes.ts
  app/screens/family/ChooseFamilyPage.tsx
  app/screens/family/CreateFamilyPage.tsx
  app/screens/family/JoinFamilyPage.tsx
  app/screens/family/components/FamilyButton.tsx
  app/screens/login/LoginPage.tsx
Labels: refacto

#46 Style: Background de l'app
  App.tsx
  app/screens/login/components/AuthCard.tsx
  app/theme/ThemeProvider.tsx
Labels: enhancement

#49 Feat: Ajout des chargements
  app/components/CustomLoader.tsx
  app/screens/family/CreateFamilyPage.tsx
  app/screens/family/JoinFamilyPage.tsx
  app/screens/login/LoginPage.tsx
  app/screens/login/components/AuthCard.tsx
Labels: enhancement

#50 Feat: Get UserInformation Page
  App.tsx
  app/components/Inputs/CustomDatePicker.tsx
  app/navigation/routes.ts
  app/screens/onBoarding/GetUserInformationPage.tsx
  app/screens/onBoarding/LoginPage.tsx
  app/screens/onBoarding/components/AuthCard.tsx
  package.json
  yarn.lock
Labels: enhancement

#52 FEAT: creation de la page profil
  App.tsx
  app/components/Inputs/CustomTextField.tsx
  app/screens/account/AccountPage.tsx
  app/screens/account/components/AccountCard.tsx
  app/screens/account/components/ImagePickerPopUp.tsx
  app/screens/account/components/PopUpButton.tsx
  assets/defaultProfile.jpg
  package.json
  yarn.lock
Labels: enhancement

#57 Fix: ombre des boutons
  App.tsx
  app/screens/family/components/FamilyButton.tsx
Labels: bug

#58 Feat: ajout du datepicker
  App.tsx
  app/screens/account/AccountPage.tsx
  app/screens/account/components/AccountCard.tsx
Labels: enhancement

#59 Fix: le clavier en majuscule dans le text field du rejoindre une famille
  app/screens/family/JoinFamilyPage.tsx
Labels: bug

#66 Fix: ecran qui tremble
  app/screens/account/AccountPage.tsx
  app/screens/family/JoinFamilyPage.tsx
Labels: bug

#67 Feat (Stats): Ajout Page Statistique
  App.tsx
  app/components/Content/PieceComponent.tsx
  app/components/Content/ProfilePicture.tsx
  app/navigation/routes.ts
  app/screens/stats/FamilyStatsPage.tsx
  app/screens/stats/components/FamilyStatsCard.tsx
  app/screens/stats/components/FamilyStatsHeader.tsx
  app/screens/stats/components/FamilyStatsList.tsx
  package.json
  yarn.lock
Labels: enhancement

#69 feat: ajout de la page Mes Tâches
  App.tsx
  app/components/Content/CarIcon.tsx
  app/components/Content/HouseHoldIcon.tsx
  app/components/Content/ShoppingIcon.tsx
  app/navigation/routes.ts
  app/screens/task/TaskPage.tsx
  app/screens/task/components/TaskItemComponent.tsx
  app/screens/task/components/TitleComponent.tsx
Labels: enhancement

#71 Feat: HomePage
  App.tsx
  app/components/Content/HeaderIcon.tsx
  app/components/Content/ProfilePicture.tsx
  app/navigation/routes.ts
  app/screens/home/HomePage.tsx
  app/screens/home/components/HomePageHeader.tsx
  app/screens/home/components/HomePageMenuItem.tsx
  app/screens/home/components/HomePageStatsHeader.tsx
  app/screens/task/TaskPage.tsx
  app/screens/task/components/TaskItemComponent.tsx
Labels: enhancement

#81 Feat: Navigation + Retour en arrière
  App.tsx
  app/components/GoBackButton.tsx
  app/hooks/Family.ts
  app/navigation/routes.ts
  app/screens/family/CreateFamilyPage.tsx
  app/screens/family/JoinFamilyPage.tsx
  app/screens/home/HomePage.tsx
  app/screens/home/components/HomePageHeader.tsx
  app/screens/onBoarding/GetUserInformationPage.tsx
  app/screens/onBoarding/LoginPage.tsx
  app/screens/stats/FamilyStatsPage.tsx
  app/screens/task/TaskPage.tsx
Labels: enhancement

#84 Feat: Ajout du score sur la HomePage
  app/screens/home/components/HomePageStatsHeader.tsx
  app/screens/stats/components/FamilyStatsHeader.tsx
Labels: enhancement

#85 Style: changement icon leaderboard en trophy
  app/screens/home/components/HomePageHeader.tsx
Labels: enhancement

#87 Feat: Déconnexion
  App.tsx
  app/components/GoBackButton.tsx
  app/components/Inputs/CustomIconButton.tsx
  app/navigation/routes.ts
  app/screens/account/AccountPage.tsx
  app/screens/settings/SettingsPage.tsx
  app/screens/settings/components/SettingsButton.tsx
Labels: enhancement

#88 10 feat add task page
  App.tsx
  app/components/Inputs/CustomDropdown.tsx
  app/components/Inputs/CustomTextField.tsx
  app/navigation/routes.ts
  app/screens/family/CreateFamilyPage.tsx
  app/screens/home/AddTaskPage.tsx
  app/screens/home/InformationTaskPage.tsx
  app/screens/home/components/CustomRepeat.tsx
  package.json
  yarn.lock
Labels: enhancement
