Repository Teed-Corp/teedhouse, pull requests merged in 2024-05, with the labels that each got.

#101 73 feat modifier mdp
  app/components/common/Content/ErrorText.tsx
  app/navigation/RootNavigation.tsx
  app/navigation/routes.ts
  app/screens/root/AccountPage.tsx
  app/screens/root/ChangePasswordPage.tsx
  app/screens/root/HomePage.tsx
  app/screens/root/SettingsPage.tsx
Labels: enhancement

#102 fix : clavier en majuscule
  app/navigation/RootNavigation.tsx
  app/screens/onBoarding/GetUserInformationPage.tsx
Labels: bug

#103 feat : changement de l'image de profile dans l'accountPage
  app/screens/root/AccountPage.tsx
  assets/defaultProfile.jpg
Labels: enhancement

#104 feat : Ajout du style pour le Text du header
  app/components/root/Header.tsx
Labels: enhancement

#106 feat : Création de la pop-up pour l'ajout de tâche par défaut
  app/screens/onBoarding/CreateFamilyPage.tsx
Labels: enhancement

#107 95 fix datepicker difficile de changer lannée
  app/components/common/Inputs/CustomDatePicker.tsx
  app/screens/onBoarding/GetUserInformationPage.tsx
  app/screens/root/AccountPage.tsx
  app/utils/DateUtils.ts
  package.json
  yarn.lock
Labels: bug, enhancement

#111 fix: DatePicker IOS
  app/components/common/Inputs/CustomDatePicker.tsx
Labels: bug

#112 105 popup pour confirmer la réalistation dun tâche
  app/components/root/task/TaskItemComponent.tsx
Labels: enhancement

#120 119 fix titre
  app/components/common/Inputs/CustomDatePicker.tsx
  app/screens/onBoarding/CreateFamilyPage.tsx
  app/screens/root/HomePage.tsx
  app/screens/root/TaskPage.tsx
Labels: bug
